<?php
/**
 * Class Manager — Take Written Exam (take_written_exam.php)
 * 
 * Online written exam interface. Features:
 * - 40 questions (5 randomized from each of the 8 sections).
 * - Scrambled options.
 * - One question at a time wizard interface (RF-Updated).
 * - Immediate individual feedback with non-intrusive explanation card.
 * - 50-minute timer visible at all times.
 * - Multi-layered Anti-Cheat system.
 */

if (empty($_SESSION['logged_in']) || !in_array($_SESSION['usuario']['rol'] ?? '', ['alumno', 'docente', 'admin'])) {
  header('Location: index.php?page=login');
  exit;
}
?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<?php

$db = Database::getConnection();
$alumnoId = (int) ($_SESSION['alumno']['id_alumno'] ?? 0);
$grupoId = (int) ($_GET['id_grupo'] ?? 0);
$parcial = (int) ($_GET['parcial'] ?? 0);

if ($grupoId <= 0 || $parcial < 1 || $parcial > 3) {
  echo "<div class='card' style='padding: var(--space-6); text-align: center;'><h3>Parámetros de examen inválidos.</h3><a href='index.php?page=home' class='btn btn-primary'>Volver al inicio</a></div>";
  return;
}

// Check if exam is enabled/generated by teacher
$stmtGroupCycle = $db->prepare("SELECT ciclo FROM grupo WHERE id_grupo = :gid");
$stmtGroupCycle->execute([':gid' => $grupoId]);
$groupCycle = $stmtGroupCycle->fetchColumn();

$stmtConf = $db->prepare("SELECT generado, preguntas_t1, preguntas_t2, duracion, distribucion_preguntas FROM examen_config WHERE id_grupo = :gid AND parcial = :p AND ciclo = :ciclo");
$stmtConf->execute([':gid' => $grupoId, ':p' => $parcial, ':ciclo' => $groupCycle]);
$config = $stmtConf->fetch();
$isGenerated = $config ? (int) $config['generado'] : 0;
$duracion = $config ? (int) $config['duracion'] : 50;

$distribucionJson = $config ? $config['distribucion_preguntas'] : null;
if (empty($distribucionJson)) {
  $distribucion = [
    "1" => $config ? (int) $config['preguntas_t1'] : 20,
    "2" => $config ? (int) $config['preguntas_t2'] : 20
  ];
} else {
  $distribucion = json_decode($distribucionJson, true);
  if (!is_array($distribucion)) {
    $distribucion = ["1" => 20, "2" => 20];
  }
}

if (!$isGenerated) {
  echo "
    <div class='card' style='padding: var(--space-8); text-align: center; max-width: 600px; margin: 40px auto; border-radius: 16px; border: 2px solid var(--border-color); box-shadow: 0 8px 24px rgba(0,0,0,0.06);'>
        <div style='font-size: 64px; margin-bottom: var(--space-4);'>🔒</div>
        <h2 style='font-family: var(--font-heading); color: var(--color-danger); font-weight: 800; margin-bottom: var(--space-2);'>Examen no habilitado</h2>
        <p style='color: var(--gray-600); margin-bottom: var(--space-6);'>Este examen escrito aún no ha sido activado por tu profesor para el ciclo o parcial correspondiente.</p>
        <div>
            <a href='index.php?page=home' class='btn btn-primary' style='border-radius: 20px; padding: var(--space-3) var(--space-6);'>Volver al Dashboard</a>
        </div>
    </div>";
  return;
}

// Check if student has already completed this exam
$stmtCheck = $db->prepare("SELECT calificacion FROM examen_escrito WHERE id_grupo = :gid AND id_alumno = :aid AND parcial = :p");
$stmtCheck->execute([':gid' => $grupoId, ':aid' => $alumnoId, ':p' => $parcial]);
$existingGrade = $stmtCheck->fetchColumn();

if ($existingGrade !== false && $existingGrade !== null) {
  echo "
    <div class='card' style='padding: var(--space-8); text-align: center; max-width: 600px; margin: 40px auto; border-radius: 16px; border: 2px solid var(--border-color); box-shadow: 0 8px 24px rgba(0,0,0,0.06);'>
        <div style='font-size: 64px; margin-bottom: var(--space-4);'>📝</div>
        <h2 style='font-family: var(--font-heading); color: var(--uts-green); font-weight: 800; margin-bottom: var(--space-2);'>Examen ya presentado</h2>
        <p style='color: var(--gray-600); margin-bottom: var(--space-6);'>Ya has completado la evaluación escrita de este parcial. Tu calificación obtenida es:</p>
        <div style='font-size: 48px; font-weight: 900; color: var(--color-primary); font-family: var(--font-heading); margin-bottom: var(--space-6); background: #faf9f6; padding: var(--space-4); border-radius: 12px; border: 1.5px dashed var(--border-color); display: inline-block; min-width: 150px;'>
            " . number_format((float) $existingGrade, 2) . "
        </div>
        <div>
            <a href='index.php?page=home' class='btn btn-primary' style='border-radius: 20px; padding: var(--space-3) var(--space-6);'>Volver al Dashboard</a>
        </div>
    </div>";
  return;
}

$allQuestions = [];

try {
  foreach ($distribucion as $topicId => $limitTopic) {
    $topicId = (int) $topicId;
    $limitTopic = (int) $limitTopic;
    if ($limitTopic <= 0) {
      continue;
    }

    // Get sections for this topic
    $stmtSections = $db->prepare("SELECT id_seccion, letra, nombre, descripcion FROM seccion WHERE id_topico = :tid ORDER BY letra");
    $stmtSections->execute([':tid' => $topicId]);
    $sections = $stmtSections->fetchAll();

    if (empty($sections)) {
      continue;
    }

    $questionsTopic = [];
    $sectionsCount = count($sections);
    $limitPerSection = (int) ceil($limitTopic / $sectionsCount);

    foreach ($sections as $sec) {
      $stmt = $db->prepare("
          SELECT p.*, s.letra AS seccion, s.nombre AS seccion_nombre, s.descripcion AS seccion_descripcion, s.id_topico AS parte
          FROM pregunta p
          INNER JOIN seccion s ON p.id_seccion = s.id_seccion
          WHERE s.id_seccion = :sid
          ORDER BY RAND()
          LIMIT :lim
      ");
      $stmt->bindValue(':sid', $sec['id_seccion'], PDO::PARAM_INT);
      $stmt->bindValue(':lim', $limitPerSection, PDO::PARAM_INT);
      $stmt->execute();
      $questions = $stmt->fetchAll();
      foreach ($questions as $q) {
        $questionsTopic[] = $q;
      }
    }

    shuffle($questionsTopic);
    $questionsTopic = array_slice($questionsTopic, 0, $limitTopic);
    $allQuestions = array_merge($allQuestions, $questionsTopic);
  }

  // Shuffle all questions globally
  shuffle($allQuestions);
} catch (Exception $e) {
  echo "<div class='card'><h3>Error al cargar el banco de preguntas: " . htmlspecialchars($e->getMessage()) . "</h3></div>";
  return;
}
?>

<div id="welcome-card" class="card"
  style="max-width: 650px; margin: 40px auto; padding: var(--space-8); border-radius: 16px; border: 2px solid var(--border-color); box-shadow: 0 10px 30px rgba(0,0,0,0.08); text-align: center; background: var(--card-bg);">
  <h2
    style="font-family: var(--font-heading); color: var(--primary-800); font-weight: 800; margin-bottom: var(--space-3); font-size: 26px;">
    Instrucciones</h2>

  <div
    style="text-align: left; background: #faf9f6; padding: var(--space-5); border-radius: 12px; border: 1.5px dashed var(--border-color); margin-bottom: var(--space-6); font-size: var(--text-sm); line-height: 1.6; color: var(--gray-700);">
    <p style="margin-top: 0; font-weight: 700;">Estás a punto de iniciar tu examen, lee atentamente las siguientes
      instrucciones antes de comenzar:</p>
    <ul
      style="padding-left: var(--space-4); margin-bottom: 0; display: flex; flex-direction: column; gap: var(--space-2);">
      <li><strong>Oportunidad única:</strong> Cuentas con <strong>una sola oportunidad</strong> para realizar este
        examen.</li>
      <li><strong>Límite de tiempo:</strong> Tienes un máximo de <strong><?= $duracion ?> minutos</strong> para
        completarlo. Si el
        tiempo expira, tus respuestas se guardarán y enviarán automáticamente.</li>
      <li><strong>Bloqueo de navegación:</strong> Si retrocedes en el navegador, intentas salir, recargas la página o
        cierras la pestaña, <strong>el examen se registrará como no completado (0.00)</strong> y no podrás volver a
        ingresar.</li>
    </ul>
  </div>

  <div style="display: flex; justify-content: space-between; align-items: center; margin-top: var(--space-6);">
    <a href="index.php?page=home" class="btn btn-outline"
      style="border-radius: 20px; font-weight: bold; padding: var(--space-3) var(--space-8); font-size: var(--text-md); text-decoration: none; display: inline-flex; align-items: center; justify-content: center; height: 42px; box-sizing: border-box;">
      Cancelar
    </a>
    <button type="button" class="btn btn-primary" onclick="startOfficialExam()"
      style="border-radius: 20px; font-weight: bold; padding: var(--space-3) var(--space-8); font-size: var(--text-md); box-shadow: 0 4px 12px rgba(10,111,81,0.2); height: 42px; box-sizing: border-box; display: inline-flex; align-items: center; justify-content: center;">
      Comenzar
    </button>
  </div>
</div>

<div class="take-exam-wrapper notranslate" translate="no"
  style="user-select: none; -webkit-user-select: none; display: none;" oncopy="return false;" oncut="return false;"
  onpaste="return false;" oncontextmenu="return false;">

  <!-- Sticky/Fixed Sub-Header Bar (Discreet, representing baseline/encabezado_examen.png) -->
  <div class="exam-sticky-bar"
    style="position: sticky; top: var(--header-height); z-index: 99; background: var(--bg-surface, #ffffff); border-bottom: 2px solid var(--border-color); box-shadow: var(--shadow-sm); padding: var(--space-4) var(--space-6); margin: 0 0 var(--space-6) 0; border-radius: 16px; border: 1.5px solid var(--border-color);">
    <!-- Row 1: Examen Parcial 1 & Tiempo Restante -->
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: var(--space-3);">
      <div style="display: flex; align-items: center; gap: var(--space-3);">
        <h2
          style="font-family: var(--font-heading); font-size: 22px; font-weight: 800; color: var(--primary-800); margin: 0; line-height: 1;">
          Examen Parcial <?= $parcial ?></h2>
        <span class="exam-badge"
          style="background: rgba(10,111,81,0.1); color: var(--uts-green); padding: 3px 10px; border-radius: 12px; font-size: 10px; font-weight: 800; text-transform: uppercase; line-height: 1; letter-spacing: 0.5px;">Evaluación
          Escrita</span>
      </div>
      <div style="text-align: right; display: flex; align-items: center; gap: var(--space-3);">
        <span
          style="font-size: 11px; font-weight: 800; text-transform: uppercase; color: var(--gray-400); letter-spacing: 0.5px;">Tiempo
          Restante</span>
        <span id="exam-timer"
          style="font-size: 26px; font-weight: 900; color: var(--uts-green); font-family: var(--font-heading); line-height: 1; background: rgba(10,111,81,0.05); padding: 6px 12px; border-radius: 8px; border: 1px solid rgba(10,111,81,0.12);"><?= sprintf('%02d:00', $duracion) ?></span>
      </div>
    </div>

    <!-- Row 2: Progreso del Examen & Pregunta X de Y -->
    <div style="display: flex; justify-content: space-between; align-items: center; gap: var(--space-4);">
      <div style="flex: 1; display: flex; align-items: center; gap: var(--space-3);">
        <span
          style="font-size: 11px; font-weight: 800; color: var(--gray-500); text-transform: uppercase; letter-spacing: 0.5px; white-space: nowrap;">Progreso
          del Examen</span>
        <div style="flex: 1; height: 8px; background: var(--border-color); border-radius: 4px; overflow: hidden;">
          <div id="exam-progress-bar"
            style="width: <?= round(100 / count($allQuestions), 2) ?>%; height: 100%; background: linear-gradient(90deg, var(--uts-green), #149b6e); transition: width 0.3s ease; border-radius: 4px;">
          </div>
        </div>
      </div>
      <span id="progress-text"
        style="font-size: 12px; font-weight: 800; color: var(--gray-600); white-space: nowrap;">Pregunta 1 de
        <?= count($allQuestions) ?></span>
    </div>
  </div>

  <!-- Questions Wizard -->
  <form id="written-exam-form">
    <input type="hidden" name="id_grupo" value="<?= $grupoId ?>">
    <input type="hidden" name="parcial" value="<?= $parcial ?>">

    <div class="wizard-questions-container">
      <?php foreach ($allQuestions as $index => $q):
        // Fetch options
        $stmtOpts = $db->prepare("SELECT * FROM opcion WHERE id_pregunta = :qid");
        $stmtOpts->execute([':qid' => $q['id_pregunta']]);
        $options = $stmtOpts->fetchAll();

        // Shuffle options
        shuffle($options);

        // Get correct option ID and text to compare client side
        $correctOptId = 0;
        $correctOptText = '';
        foreach ($options as $opt) {
          if ($opt['es_correcta']) {
            $correctOptId = $opt['id_opcion'];
            $correctOptText = $opt['texto'];
          }
        }
        ?>
        <div class="card exam-question-card" id="q-card-<?= $q['id_pregunta'] ?>" data-question-index="<?= $index ?>"
          data-correct-id="<?= $correctOptId ?>" data-correct-text="<?= htmlspecialchars($correctOptText) ?>"
          data-part="<?= $q['parte'] ?>" data-section="<?= $q['seccion'] ?>"
          style="border: 2px solid var(--border-color); border-radius: 12px; padding: var(--space-6); background: var(--card-bg); display: <?= $index === 0 ? 'block' : 'none' ?>;">

          <!-- Instruction box -->
          <div
            style="background: rgba(10,111,81,0.03); border-left: 3.5px solid var(--uts-green); padding: var(--space-2) var(--space-4); border-radius: 6px; margin-bottom: var(--space-4); box-shadow: inset 0 1px 3px rgba(0,0,0,0.01);">
            <div
              style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: var(--uts-green); letter-spacing: 0.5px; margin-bottom: 2px;">
              <?= htmlspecialchars(strtoupper($q['seccion_nombre'] === 'Theoretical' ? 'THEORETICAL REASONING & CONCEPT MATCHING' : $q['seccion_nombre'])) ?>
            </div>
            <div style="font-size: 11px; color: var(--gray-600); font-weight: 600; line-height: 1.45;">
              <?= htmlspecialchars($q['seccion_descripcion']) ?>
            </div>
          </div>

          <div style="display: flex; gap: var(--space-3); margin-bottom: var(--space-4);">
            <span
              style="background: var(--uts-green); color: white; font-weight: 800; font-size: var(--text-sm); width: 28px; height: 28px; display: inline-flex; align-items: center; justify-content: center; border-radius: 50%; flex-shrink: 0; font-family: monospace; border: 1.5px solid var(--uts-green);">
              <?= $index + 1 ?>
            </span>
            <div>
              <h3
                style="font-size: var(--text-md); font-weight: 700; color: var(--gray-800); line-height: 1.5; margin: 0;">
                <?php
                if ($q['seccion'] === 'C') {
                  echo preg_replace('/((?:[a-zA-Z0-9\'-]+\s+){0,2}[a-zA-Z0-9\'-]+)\s*\(([A-C])\)/u', '<u style="text-decoration: underline; text-decoration-color: var(--uts-gold); text-underline-offset: 4px; font-weight: 700;">$1</u> <b>($2)</b>', htmlspecialchars($q['texto']));
                } else {
                  echo htmlspecialchars($q['texto']);
                }
                ?>
              </h3>
              <span
                style="display: inline-block; font-size: 10px; color: var(--gray-400); text-transform: uppercase; font-weight: bold; margin-top: var(--space-1);">
                Parte <?= $q['parte'] ?> • Sección <?= $q['seccion'] ?>
              </span>
            </div>
          </div>

          <!-- Options List -->
          <div class="options-list-container" id="opts-container-<?= $q['id_pregunta'] ?>"
            style="display: flex; flex-direction: column; gap: var(--space-2); margin-left: 0;">
            <?php foreach ($options as $opt): ?>
              <label class="exam-option-label" id="opt-label-<?= $opt['id_opcion'] ?>"
                style="display: flex; align-items: center; gap: var(--space-3); padding: var(--space-3) var(--space-4); border: 1.5px solid var(--border-color); border-radius: 10px; cursor: pointer; transition: all 0.2s; background: #faf9f6; font-size: var(--text-sm); font-weight: 500; color: var(--gray-700); margin: 0; user-select: none;">
                <input type="radio" name="answers[<?= $q['id_pregunta'] ?>]" value="<?= $opt['id_opcion'] ?>"
                  onclick="selectOption(<?= $q['id_pregunta'] ?>, <?= $opt['id_opcion'] ?>)"
                  style="width: 18px; height: 18px; accent-color: var(--uts-green); margin: 0;">
                <span><?= htmlspecialchars($opt['texto']) ?></span>
              </label>
            <?php endforeach; ?>
          </div>

          <!-- Explanations / Feedback Panel (Hidden initially) -->
          <div class="feedback-panel" id="feedback-<?= $q['id_pregunta'] ?>"
            style="display: none; margin-top: var(--space-5); margin-left: 0; padding: var(--space-4); border-radius: 10px; border-left: 4px solid var(--border-color); font-size: var(--text-sm); line-height: 1.5; animation: slideDown 0.3s ease;">
            <div style="font-weight: 700; margin-bottom: var(--space-2);" class="feedback-title"></div>
            <div class="feedback-explanation"></div>
          </div>

          <!-- Next/Submit Button for the wizard -->
          <div style="margin-top: var(--space-6); text-align: right;">
            <button type="button" id="btn-next-<?= $q['id_pregunta'] ?>"
              onclick="confirmAndNext(<?= $q['id_pregunta'] ?>, <?= $index ?>)" class="btn btn-primary" disabled
              style="border-radius: 20px; font-weight: bold; padding: var(--space-2) var(--space-6);">
              Comprobar Respuesta
            </button>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  </form>
</div>

<!-- Blur Lock overlay for anti-cheat tab-loss -->
<div id="cheat-overlay"
  style="display: none; position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.7); backdrop-filter: blur(25px); -webkit-backdrop-filter: blur(25px); z-index: 99999; align-items: center; justify-content: center; text-align: center; padding: 20px;">
  <div class="card"
    style="max-width: 500px; padding: var(--space-8); border-radius: 20px; border: 2px solid #eb5757; box-shadow: 0 12px 36px rgba(235,87,87,0.3); text-align: center;">
    <div style="font-size: 64px; color: #eb5757; margin-bottom: var(--space-4);">⚠️</div>
    <h2 style="font-family: var(--font-heading); font-weight: 800; color: #c53030; margin-bottom: var(--space-2);">
      ¡ALERTA DE SEGURIDAD!</h2>
    <p
      style="color: var(--gray-700); font-weight: 500; font-size: var(--text-sm); line-height: 1.6; margin-bottom: var(--space-6);">
      Has salido de la ventana del examen o el navegador ha perdido el foco. Esta acción queda registrada y se considera
      un intento no autorizado.
    </p>
    <button onclick="dismissCheatWarning()" class="btn btn-primary"
      style="background: #eb5757; border-color: #eb5757; border-radius: 20px; font-weight: bold; padding: var(--space-3) var(--space-6);">
      Entendido, volver al examen
    </button>
  </div>
</div>

<style>
  @keyframes slideDown {
    from {
      opacity: 0;
      transform: translateY(-10px);
    }

    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  /* Option hover styling */
  .exam-option-label:hover {
    border-color: var(--uts-green);
    background: #f0fdf4;
    transform: translateY(-1px);
  }

  .exam-option-label:has(input:checked) {
    border-color: var(--uts-green);
    background: #e6f7ed;
    color: var(--uts-green);
    font-weight: 600;
    box-shadow: 0 2px 6px rgba(10, 111, 81, 0.05);
  }

  /* Fixed locks */
  .exam-option-label.correct {
    border-color: #27ae60 !important;
    background: #eafaf1 !important;
    color: #27ae60 !important;
    font-weight: 700;
  }

  .exam-option-label.incorrect {
    border-color: #eb5757 !important;
    background: #fdf2f2 !important;
    color: #eb5757 !important;
    font-weight: 700;
  }

  .exam-option-label.disabled {
    pointer-events: none;
    opacity: 0.7;
  }

  .feedback-panel.success {
    border-color: #27ae60;
    background: #eafaf1;
    color: #1e8449;
  }

  .feedback-panel.error {
    border-color: #eb5757;
    background: #fdf2f2;
    color: #c53030;
  }

  @media (max-width: 576px) {
    .exam-badge {
      display: none !important;
    }
  }
</style>

<script>
  let totalQuestions = <?= count($allQuestions) ?>;
  let currentIndex = 0;
  let selectedOptionMap = {}; // Maps questionId -> optionId
  let answeredSet = new Set();
  let confirmedSet = new Set();
  let examTimerInterval = null;
  let examDurationMinutes = <?= $duracion ?>;
  let timeRemaining = examDurationMinutes * 60; // Dynamic duration in seconds

  // Explanations Dictionary for grammatical rules
  const explanations = {
    '1_A': "En especulación en presente, 'must' expresa una alta certeza (>90%) basada en evidencias, 'might/could/may' expresan una posibilidad del ~50%, mientras que 'can't' indica una imposibilidad lógica.",
    '1_B': "El orden correcto de las oraciones especulativas en inglés es: Sujeto + Modal + Verbo en forma base sin 'to'. Ejemplo: 'The story must be true'.",
    '1_C': "Los verbos modales son auxiliares puros: nunca añaden '-s' para terceras personas (he/she/it), siempre van seguidos de un verbo en infinitivo sin 'to' y no tienen gerundios (-ing).",
    '1_D': "Especulaciones en presente: 'Must' indica certeza de que algo es verdad, 'might'/'could' señalan posibilidad abierta, y 'can't' es la deducción lógica de que algo es imposible.",
    '2_A': "El Primer Condicional con modales expresa escenarios futuros muy posibles: se usa Presente Simple en la cláusula de la condición (If-clause) y un modal en presente + forma base en la cláusula de resultado.",
    '2_B': "Estructura del primer condicional: si se inicia con la cláusula 'If', esta se separa de la principal con una coma. Si se empieza con el resultado, no se añade coma.",
    '2_C': "Error condicional común: nunca se debe colocar 'will' o 'would' inmediatamente dentro de la cláusula condicional ('If'). El presente simple es el único tiempo correcto.",
    '2_D': "Los condicionales reales (tipo 1) se estructuran con un tiempo presente en la condición para proyectar de forma verosímil y probable un desenlace futuro."
  };

  // Prevent copy-paste and translation shortcuts
  document.addEventListener('keydown', function (e) {
    if ((e.ctrlKey || e.metaKey) && (e.key === 'c' || e.key === 'x' || e.key === 'a' || e.key === 'v' || e.key === 'p')) {
      e.preventDefault();
      return false;
    }
  });

  // Blur Detection / Anti-Cheat
  window.addEventListener('blur', function () {
    triggerCheatAlert();
  });

  function triggerCheatAlert() {
    const overlay = document.getElementById('cheat-overlay');
    overlay.style.display = 'flex';
    document.querySelector('.take-exam-wrapper').style.filter = 'blur(20px)';
  }

  function dismissCheatWarning() {
    const overlay = document.getElementById('cheat-overlay');
    overlay.style.display = 'none';
    document.querySelector('.take-exam-wrapper').style.filter = 'none';
  }

  // Option selection
  function selectOption(qId, optId) {
    selectedOptionMap[qId] = optId;

    // Enable the confirm button
    const btn = document.getElementById('btn-next-' + qId);
    if (btn) btn.disabled = false;
  }

  // Confirm answer and show immediate feedback
  function confirmAndNext(qId, index) {
    const card = document.getElementById('q-card-' + qId);
    const correctId = parseInt(card.getAttribute('data-correct-id'), 10);
    const correctText = card.getAttribute('data-correct-text');
    const part = card.getAttribute('data-part');
    const section = card.getAttribute('data-section');
    const selectedId = selectedOptionMap[qId];

    const btn = document.getElementById('btn-next-' + qId);

    if (!confirmedSet.has(qId)) {
      // --- STEP 1: CONVERT BUTTON TO SHOW FEEDBACK ---
      confirmedSet.add(qId);

      // Disable all radio buttons
      const radios = card.querySelectorAll('input[type="radio"]');
      radios.forEach(r => r.disabled = true);

      // Disable other options hover
      const labels = card.querySelectorAll('.exam-option-label');
      labels.forEach(l => l.classList.add('disabled'));

      // Check if selected is correct
      const isCorrect = (selectedId === correctId);

      // Color selected and correct labels
      labels.forEach(l => {
        const radio = l.querySelector('input');
        const val = parseInt(radio.value, 10);
        if (val === correctId) {
          l.classList.add('correct');
        } else if (val === selectedId && !isCorrect) {
          l.classList.add('incorrect');
        }
      });

      // Show non-intrusive feedback panel
      const fbPanel = document.getElementById('feedback-' + qId);
      const fbTitle = fbPanel.querySelector('.feedback-title');
      const fbExplanation = fbPanel.querySelector('.feedback-explanation');

      fbPanel.style.display = 'block';

      if (isCorrect) {
        fbPanel.classList.add('success');
        fbTitle.innerHTML = '✨ ¡Correcto!';
      } else {
        fbPanel.classList.add('error');
        fbTitle.innerHTML = '❌ Incorrecto';
      }

      // Fetch grammar explanation
      const key = part + '_' + section;
      const ruleExplanation = explanations[key] || "Explicación gramatical en base a las reglas de modales y condicionales ingleses.";

      fbExplanation.innerHTML = `<b>Respuesta correcta:</b> ${correctText}.<br><br><b>¿Por qué?</b> ${ruleExplanation}`;

      // Change button text
      if (index === totalQuestions - 1) {
        btn.innerText = 'Finalizar Examen';
      } else {
        btn.innerText = 'Siguiente Pregunta';
      }
    } else {
      // --- STEP 2: TRANSITION TO NEXT QUESTION WIZARD ---
      card.style.display = 'none';

      if (index < totalQuestions - 1) {
        // Show next card
        currentIndex = index + 1;
        const nextCardId = document.querySelectorAll('.exam-question-card')[currentIndex].id;
        const nextCard = document.getElementById(nextCardId);
        nextCard.style.display = 'block';

        // Scroll to the top of the next question card with an offset for the sticky header
        setTimeout(() => {
          const headerOffset = 180; // app header + sticky sub-header + comfort buffer
          const elementPosition = nextCard.getBoundingClientRect().top;
          const offsetPosition = elementPosition + window.pageYOffset - headerOffset;

          window.scrollTo({
            top: offsetPosition,
            behavior: 'smooth'
          });
        }, 50);

        // Update progress indicator
        updateProgress();
      } else {
        // End of exam
        sendExamDataDirect();
      }
    }
  }

  // Update progress bar
  function updateProgress() {
    let activeQuestionNum = currentIndex + 1;
    let pct = (activeQuestionNum / totalQuestions) * 100;

    document.getElementById('exam-progress-bar').style.width = pct + '%';
    document.getElementById('progress-text').innerText = 'Pregunta ' + activeQuestionNum + ' de ' + totalQuestions;
  }

  // Timer Logic
  function startTimer() {
    examTimerInterval = setInterval(function () {
      if (timeRemaining <= 0) {
        clearInterval(examTimerInterval);
        timeRemaining = 0;
        autoSubmitOnTimeout();
      } else {
        timeRemaining--;
        let mins = Math.floor(timeRemaining / 60);
        let secs = timeRemaining % 60;
        document.getElementById('exam-timer').innerText =
          (mins < 10 ? '0' : '') + mins + ':' + (secs < 10 ? '0' : '') + secs;

        // Warning color under 5 minutes
        if (timeRemaining < 300) {
          document.getElementById('exam-timer').style.color = '#eb5757';
        }
      }
    }, 1000);
  }

  function autoSubmitOnTimeout() {
    Swal.fire({
      title: '¡Tiempo agotado!',
      text: `El tiempo límite de ${examDurationMinutes} minutos ha finalizado. Tus respuestas se enviarán automáticamente.`,
      icon: 'warning',
      allowOutsideClick: false,
      confirmButtonText: 'Aceptar',
      confirmButtonColor: 'var(--uts-green)'
    }).then(() => {
      sendExamDataDirect();
    });
  }

  // Submit Data via Fetch API
  function sendExamDataDirect() {
    clearUnloadGuard();
    clearInterval(examTimerInterval);

    const form = document.getElementById('written-exam-form');
    const formData = new FormData(form);

    // Append the answers from the JavaScript map so disabled inputs are not lost
    for (const [qId, optId] of Object.entries(selectedOptionMap)) {
      formData.append(`answers[${qId}]`, optId);
    }

    // Show premium Loading Spinner
    Swal.fire({
      title: 'Guardando y calificando...',
      text: 'Por favor, no cierres esta pestaña.',
      allowOutsideClick: false,
      didOpen: () => {
        Swal.showLoading();
      }
    });

    fetch('index.php?action=submit_written_exam', {
      method: 'POST',
      body: formData
    })
      .then(response => response.json())
      .then(data => {
        if (data.success) {
          Swal.fire({
            title: '¡Examen Completado!',
            html: `Tu examen fue calificado automáticamente.<br><br>Aciertos: <b>${data.score} / ${data.total}</b><br>Calificación obtenida: <span style="font-size: 28px; font-weight: 800; color: var(--uts-green);">${data.grade}</span>`,
            icon: 'success',
            confirmButtonColor: 'var(--uts-green)',
            confirmButtonText: 'Regresar al Dashboard'
          }).then(() => {
            window.location.href = 'index.php?page=home';
          });
        } else {
          Swal.fire({
            title: 'Error',
            text: data.message || 'Hubo un error al procesar el examen.',
            icon: 'error',
            confirmButtonColor: '#eb5757',
            confirmButtonText: 'Volver a intentar'
          }).then(() => {
            window.location.reload();
          });
        }
      })
      .catch(error => {
        Swal.fire({
          title: 'Error de Red',
          text: 'No se pudo conectar al servidor. Revisa tu conexión a Internet.',
          icon: 'error',
          confirmButtonColor: '#eb5757',
          confirmButtonText: 'Reintentar'
        });
      });
  }

  // Start official exam on Welcome card click
  let examStarted = false;

  function startOfficialExam() {
    examStarted = true;

    // Hide welcome card, show exam
    document.getElementById('welcome-card').style.display = 'none';
    document.querySelector('.take-exam-wrapper').style.display = 'block';

    // Scroll to the absolute top of the page instantly to prevent layout jump
    window.scrollTo(0, 0);

    // Double check scroll position after rendering to ensure it's at the absolute top
    setTimeout(() => {
      window.scrollTo({
        top: 0,
        behavior: 'auto'
      });
    }, 30);

    // Start timer
    startTimer();

    // Prevent back/forward navigation using popstate history lock
    history.pushState(null, null, location.href);
    window.addEventListener('popstate', function () {
      history.pushState(null, null, location.href);
      Swal.fire({
        title: '⚠️ Navegación Bloqueada',
        text: 'Durante el examen no se permite retroceder ni avanzar en la navegación.',
        icon: 'warning',
        confirmButtonColor: 'var(--uts-green)',
        confirmButtonText: 'Continuar Examen'
      });
    });
  }

  // Window Unload Guard
  window.addEventListener('beforeunload', function (e) {
    if (examStarted && confirmedSet.size < totalQuestions) {
      e.preventDefault();
      e.returnValue = 'Si sales del examen, tus respuestas se perderán y se registrará como no completado. ¿Estás seguro?';
      return e.returnValue;
    }
  });

  // Clear unload event listener on successful complete submit
  function clearUnloadGuard() {
    examStarted = false;
  }
</script>